import { Platform, StyleSheet } from 'react-native';

import { LIGHT, Palette } from './palette';

// 앱 전역 글자 확대 배율. 실기기 가독성 개선을 위해 모든 명시적 fontSize를
// 한 곳에서 일률적으로 키운다(체크/토글과의 균형은 컴포넌트 쪽에서 함께 조정).
export const FONT_SCALE = 1.15;

// StyleSheet 생성 직전에 모든 fontSize를 FONT_SCALE배로 스케일하고, 명시적
// lineHeight도 같은 비율로 보정해 세로 리듬을 유지한다.
function scaleTypography<T extends Record<string, any>>(defs: T): T {
  for (const key of Object.keys(defs)) {
    const s = defs[key];
    if (s && typeof s.fontSize === 'number') {
      const next = Math.round(s.fontSize * FONT_SCALE);
      if (typeof s.lineHeight === 'number') {
        s.lineHeight = Math.round(s.lineHeight * (next / s.fontSize));
      }
      s.fontSize = next;
    }
  }
  return defs;
}

// LUCENT StyleSheet factory, extracted from the screen monolith. Depends only
// on the palette + RN primitives (Platform/StyleSheet), so it stands alone.
export const makeStyles = (C: Palette) =>
  StyleSheet.create(scaleTypography({
  app: { flex: 1, backgroundColor: C.background },
  onboardingApp: { flex: 1, backgroundColor: C.background },
  onboardingContent: { padding: 22, paddingBottom: 40 },
  onboardingBrand: { alignItems: 'center', paddingVertical: 28 },
  onboardingLogo: {
    width: 62,
    height: 62,
    borderRadius: 22,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  onboardingTitle: { color: C.navy, fontSize: 27, fontWeight: '900' },
  onboardingSubtitle: {
    color: C.textMuted,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 21,
  },
  onboardingChoice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: C.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.outline,
    padding: 18,
    minHeight: 96,
    marginBottom: 12,
  },
  onboardingChoiceTitle: { color: C.navy, fontSize: 17, fontWeight: '800' },
  onboardingChoiceText: {
    color: C.textMuted,
    lineHeight: 19,
    marginTop: 4,
  },
  onboardingForm: {
    backgroundColor: C.surface,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: C.outline,
  },
  onboardingSectionTitle: {
    color: C.navy,
    fontSize: 16,
    fontWeight: '800',
    marginTop: 8,
    marginBottom: 9,
  },
  onboardingInput: {
    minHeight: 52,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.outline,
    backgroundColor: C.background,
    paddingHorizontal: 14,
    color: C.text,
    marginBottom: 10,
  },
  energyRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 10 },
  energyChip: {
    paddingHorizontal: 12,
    minHeight: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: C.outline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  energyChipActive: {
    backgroundColor: C.primaryContainer,
    borderColor: C.primary,
  },
  energyChipText: { color: C.textMuted, fontSize: 12, fontWeight: '700' },
  energyChipTextActive: { color: C.primary },
  onboardingPrivacy: {
    color: C.textMuted,
    fontSize: 12,
    lineHeight: 18,
    marginVertical: 10,
  },
  mainContent: { flex: 1 },
  flex: { flex: 1 },
  screenContent: { paddingHorizontal: 18, paddingBottom: 28 },
  calendarModeRow: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 18,
    backgroundColor: C.surfaceAlt,
    marginBottom: 12,
  },
  calendarModeButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarModeButtonActive: {
    backgroundColor: C.surface,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  calendarModeText: { color: C.textMuted, fontWeight: '700' },
  calendarModeTextActive: { color: C.primary },
  calendarCard: {
    backgroundColor: C.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: C.outline,
    padding: 14,
    marginBottom: 22,
  },
  calendarToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  calendarTitle: { fontSize: 18, color: C.navy, fontWeight: '800' },
  calendarWeekHeader: { flexDirection: 'row', marginBottom: 5 },
  calendarWeekLabel: {
    width: '14.2857%',
    textAlign: 'center',
    color: C.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarDay: {
    width: '14.2857%',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    gap: 2,
  },
  calendarDayWide: { minHeight: 64 },
  calendarDaySelected: { backgroundColor: C.primaryContainer },
  calendarDayText: { color: C.text, fontWeight: '700' },
  calendarDayOutside: { color: '#B7C0CE' },
  calendarDayTextSelected: { color: C.onPrimaryContainer },
  calendarCount: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarCountUrgent: { backgroundColor: C.danger },
  calendarCountText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800' },
  calendarMoneyStack: {
    width: '100%',
    paddingHorizontal: 2,
    alignItems: 'center',
    gap: 1,
  },
  calendarNetText: {
    color: C.success,
    fontSize: 10,
    fontWeight: '900',
  },
  calendarNetTextNegative: { color: C.danger },
  calendarNetTextUrgent: { color: C.warning },
  calendarFuelText: {
    color: C.textMuted,
    fontSize: 8,
    fontWeight: '700',
  },
  profitSummaryCard: {
    backgroundColor: C.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.outline,
    padding: 18,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
  },
  profitSummaryLabel: { color: C.textMuted, fontSize: 12, fontWeight: '700' },
  profitSummaryValue: {
    color: C.success,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  profitSummaryValueNegative: { color: C.danger },
  profitSummaryMeta: { justifyContent: 'center', alignItems: 'flex-end', gap: 4 },
  profitSummaryMetaText: { color: C.textMuted, fontSize: 11, fontWeight: '700' },
  calendarEmpty: {
    backgroundColor: C.surface,
    borderRadius: 22,
    padding: 28,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.outline,
  },
  calendarEmptyTitle: {
    marginTop: 10,
    fontSize: 16,
    color: C.navy,
    fontWeight: '800',
  },
  calendarEmptyText: {
    marginTop: 5,
    color: C.textMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  calendarAgendaCard: {
    flexDirection: 'row',
    backgroundColor: C.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.outline,
    padding: 16,
    marginBottom: 10,
  },
  calendarAgendaCardConflict: {
    borderColor: C.warning,
    backgroundColor: C.warningBg,
  },
  calendarAgendaCardLate: {
    borderColor: C.danger,
  },
  calendarTimeColumn: { width: 86, paddingRight: 12 },
  calendarAgendaTime: { fontSize: 16, color: C.primary, fontWeight: '900' },
  calendarPrecision: {
    marginTop: 4,
    color: C.textMuted,
    fontSize: 10,
    fontWeight: '700',
  },
  calendarAgendaBody: { flex: 1 },
  calendarAgendaTitle: { color: C.navy, fontSize: 16, fontWeight: '800' },
  calendarAgendaAddress: {
    marginTop: 5,
    color: C.textMuted,
    lineHeight: 19,
  },
  calendarMetaRow: { flexDirection: 'row', gap: 12, marginTop: 8 },
  calendarUrgentText: { color: C.danger, fontSize: 12, fontWeight: '800' },
  calendarEventText: { color: C.warning, fontSize: 12, fontWeight: '800' },
  calendarConflictText: { color: C.warning, fontSize: 12, fontWeight: '900' },
  calendarLateText: { color: C.danger, fontSize: 12, fontWeight: '900' },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'android' ? 18 : 8,
    paddingBottom: 18,
  },
  headerCopy: { flex: 1, paddingRight: 12 },
  eyebrow: {
    color: C.primary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
    marginBottom: 5,
  },
  screenTitle: { color: C.text, fontSize: 27, fontWeight: '800', letterSpacing: -0.7 },
  screenSubtitle: { color: C.textMuted, fontSize: 12, lineHeight: 18, marginTop: 5 },
  headerAction: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationCounter: {
    position: 'absolute',
    right: -3,
    top: -4,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    backgroundColor: C.danger,
    borderWidth: 2,
    borderColor: C.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationCounterText: { color: '#FFFFFF', fontSize: 9, fontWeight: '800' },
  sectionHeader: {
    marginTop: 24,
    marginBottom: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: { color: C.text, fontSize: 18, fontWeight: '800', letterSpacing: -0.3 },
  sectionCaption: { color: C.textMuted, fontSize: 11, marginTop: 3 },
  metricsGrid: { flexDirection: 'row', gap: 9 },
  metricCard: {
    flex: 1,
    minHeight: 122,
    padding: 14,
    borderRadius: 20,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
  },
  metricIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 13,
  },
  metricValue: { color: C.text, fontSize: 22, fontWeight: '800' },
  metricLabel: { color: C.textMuted, fontSize: 10, fontWeight: '600', marginTop: 3 },
  progressCard: {
    marginTop: 11,
    padding: 18,
    borderRadius: 22,
    backgroundColor: C.emphasis,
  },
  progressTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  progressLabel: { color: '#BFCBE0', fontSize: 11, fontWeight: '600' },
  progressValue: { color: '#FFFFFF', fontSize: 28, fontWeight: '800', marginTop: 3 },
  progressSummary: { alignItems: 'flex-end' },
  progressSummaryValue: { color: '#FFFFFF', fontSize: 17, fontWeight: '800' },
  progressSummaryLabel: { color: '#9EADC7', fontSize: 9, marginTop: 2 },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: '#35445F',
    marginTop: 15,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 4, backgroundColor: '#7FA7FF' },
  progressMeta: { flexDirection: 'row', gap: 18, marginTop: 13 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  metaText: { color: C.textMuted, fontSize: 10, fontWeight: '600' },
  timeAlert: {
    minHeight: 92,
    borderRadius: 20,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 9,
    borderWidth: 1,
  },
  deadlineAlert: { backgroundColor: C.warningBg, borderColor: C.warning },
  eventAlert: { backgroundColor: C.dangerBg, borderColor: C.danger },
  timeIcon: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  timeAlertLabel: { fontSize: 9, fontWeight: '800', letterSpacing: 0.3 },
  timeAlertTitleRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8, marginTop: 4 },
  timeAlertTime: { color: C.text, fontSize: 20, fontWeight: '900' },
  timeAlertTitle: { flex: 1, color: C.text, fontSize: 13, fontWeight: '700' },
  timeAlertAddress: { color: C.textMuted, fontSize: 10, marginTop: 4 },
  textButton: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 40, paddingHorizontal: 5 },
  textButtonLabel: { color: C.primary, fontSize: 11, fontWeight: '800' },
  surfaceCard: {
    borderRadius: 22,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
    overflow: 'hidden',
  },
  compactDelivery: { minHeight: 104, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  sequenceMarker: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sequenceMarkerText: { color: C.onPrimary, fontSize: 13, fontWeight: '800' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  compactTime: { color: C.primary, fontSize: 11, fontWeight: '800' },
  compactTitle: { color: C.text, fontSize: 14, fontWeight: '800', marginTop: 5 },
  compactAddress: { color: C.textMuted, fontSize: 10, marginTop: 4 },
  inlineUrgent: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 7 },
  inlineUrgentText: { color: C.danger, fontSize: 10, fontWeight: '800' },
  divider: { height: 1, backgroundColor: C.outline, marginLeft: 14 },
  badge: {
    height: 26,
    paddingHorizontal: 9,
    borderRadius: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  successBadge: { backgroundColor: C.successBg },
  waitBadge: { backgroundColor: C.primaryContainer },
  badgeDot: { width: 6, height: 6, borderRadius: 3 },
  badgeText: { fontSize: 9, fontWeight: '800' },
  filterSegment: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 16,
    backgroundColor: C.surfaceAlt,
    marginBottom: 14,
  },
  filterItem: { flex: 1, minHeight: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  filterItemSelected: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.outline },
  filterText: { color: C.textMuted, fontSize: 11, fontWeight: '700' },
  filterTextSelected: { color: C.primary, fontWeight: '800' },
  deliveryList: { gap: 11 },
  deliveryCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
  },
  deliveryCardTitleGroup: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 11, paddingRight: 8 },
  destinationIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: C.primaryContainer, alignItems: 'center', justifyContent: 'center' },
  destinationIconUrgent: { backgroundColor: C.dangerBg },
  destinationName: { color: C.text, fontSize: 15, fontWeight: '800' },
  destinationVendor: { color: C.textMuted, fontSize: 10, marginTop: 3 },
  deliveryAddress: { color: C.textMuted, fontSize: 11, marginTop: 13, lineHeight: 17 },
  deliveryTimeGrid: { flexDirection: 'row', gap: 7, marginTop: 14 },
  deliveryTimeCell: { flex: 1, minHeight: 60, padding: 9, borderRadius: 14, backgroundColor: C.surfaceAlt },
  deliveryTimeCellLabel: { color: C.textMuted, fontSize: 8, fontWeight: '700' },
  deliveryTimeCellValue: { color: C.text, fontSize: 13, fontWeight: '800', marginTop: 7 },
  warningText: { color: C.warning },
  dangerText: { color: C.danger },
  deliveryCardFooter: { marginTop: 13, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.outline, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  outlinedButton: { minHeight: 40, paddingHorizontal: 13, borderRadius: 13, borderWidth: 1, borderColor: '#AFC2EB', flexDirection: 'row', alignItems: 'center', gap: 4 },
  outlinedButtonText: { color: C.primary, fontSize: 10, fontWeight: '800' },
  mapCard: { height: 315, borderRadius: 24, backgroundColor: '#E8EDF0', borderWidth: 1, borderColor: C.outline, overflow: 'hidden' },
  mapRoad: { position: 'absolute', backgroundColor: '#FFFFFF', borderColor: '#D7DEE4', borderWidth: 1, borderRadius: 20 },
  mapRoadOne: { width: '120%', height: 25, left: '-10%', top: '52%', transform: [{ rotate: '-16deg' }] },
  mapRoadTwo: { width: 24, height: '120%', left: '54%', top: '-10%', transform: [{ rotate: '18deg' }] },
  mapRoadThree: { width: '70%', height: 15, left: '15%', top: '26%', transform: [{ rotate: '8deg' }] },
  mapPark: { position: 'absolute', width: 130, height: 90, borderRadius: 50, backgroundColor: '#D8E7D7', left: -30, bottom: 10 },
  routeLineVisual: { position: 'absolute', height: 5, borderRadius: 3, backgroundColor: C.primary },
  routeArrow: { position: 'absolute', width: 22, height: 22, borderRadius: 11, backgroundColor: C.primary, borderWidth: 2, borderColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  currentLocation: { position: 'absolute', width: 24, height: 24, borderRadius: 12, backgroundColor: '#BBD0FF', alignItems: 'center', justifyContent: 'center' },
  currentLocationInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.primary, borderWidth: 2, borderColor: '#FFFFFF' },
  mapPin: { position: 'absolute', width: 36, height: 36, borderRadius: 18, backgroundColor: C.primary, borderWidth: 3, borderColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  mapPinText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  mapLegend: { position: 'absolute', left: 12, bottom: 12, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,0.92)', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10 },
  googleDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.primary },
  mapLegendText: { color: C.text, fontSize: 9, fontWeight: '700' },
  nextDestinationCard: { marginTop: 11, padding: 17, borderRadius: 22, backgroundColor: C.surface, borderWidth: 1, borderColor: C.outline },
  nextDestinationHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  nextBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: C.primaryContainer },
  nextBadgeText: { color: C.primary, fontSize: 9, fontWeight: '800' },
  nextEta: { color: C.textMuted, fontSize: 10, fontWeight: '600' },
  nextTitle: { color: C.text, fontSize: 19, fontWeight: '800', marginTop: 14 },
  nextAddress: { color: C.textMuted, fontSize: 11, marginTop: 5 },
  nextInfoRow: { flexDirection: 'row', marginTop: 17, paddingVertical: 13, borderTopWidth: 1, borderBottomWidth: 1, borderColor: C.outline },
  nextInfo: { flex: 1 },
  nextInfoLabel: { color: C.textMuted, fontSize: 8, fontWeight: '700' },
  nextInfoValue: { color: C.text, fontSize: 14, fontWeight: '800', marginTop: 5 },
  nextInfoDivider: { width: 1, backgroundColor: C.outline, marginHorizontal: 10 },
  priorityNotice: { marginTop: 13, padding: 11, borderRadius: 13, backgroundColor: C.dangerBg, flexDirection: 'row', alignItems: 'center', gap: 8 },
  priorityNoticeText: { flex: 1, color: C.danger, fontSize: 10, fontWeight: '700', lineHeight: 15 },
  routeButtons: { flexDirection: 'row', gap: 9, marginTop: 14 },
  routeStackRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 14, gap: 12 },
  routeStackOrder: { width: 26, height: 26, borderRadius: 13, backgroundColor: C.primaryContainer, alignItems: 'center', justifyContent: 'center' },
  routeStackOrderText: { color: C.primary, fontSize: 12, fontWeight: '800' },
  routeStackBody: { flex: 1 },
  routeStackTitle: { color: C.text, fontSize: 14, fontWeight: '700' },
  routeStackAddress: { color: C.textMuted, fontSize: 11, marginTop: 2 },
  routeStackControls: { flexDirection: 'row', gap: 4 },
  routeStackArrow: { width: 34, height: 34, borderRadius: 11, backgroundColor: C.surfaceAlt, alignItems: 'center', justifyContent: 'center' },
  navAppOptions: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingBottom: 14 },
  navAppOption: { flex: 1, minHeight: 44, borderRadius: 13, borderWidth: 1, borderColor: C.outline, backgroundColor: C.surface, alignItems: 'center', justifyContent: 'center' },
  navAppOptionActive: { borderColor: C.primary, backgroundColor: C.primaryContainer },
  navAppOptionText: { color: C.textMuted, fontSize: 13, fontWeight: '700' },
  navAppOptionTextActive: { color: C.primary, fontWeight: '800' },
  primaryButton: { flex: 1, minHeight: 48, borderRadius: 15, backgroundColor: C.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 12 },
  primaryButtonText: { color: C.onPrimary, fontSize: 11, fontWeight: '800' },
  secondaryButton: { flex: 1, minHeight: 48, borderRadius: 15, backgroundColor: C.primaryContainer, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 12 },
  secondaryButtonText: { color: C.primary, fontSize: 11, fontWeight: '800' },
  notificationSummary: { minHeight: 95, borderRadius: 22, padding: 17, backgroundColor: C.emphasis, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  notificationSummaryLabel: { color: '#BFCBE0', fontSize: 10 },
  notificationSummaryValue: { color: '#FFFFFF', fontSize: 25, fontWeight: '800', marginTop: 5 },
  urgencyLegend: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendDot: { width: 7, height: 7, borderRadius: 4, marginLeft: 6 },
  legendText: { color: '#D2DBEB', fontSize: 9 },
  notificationList: { gap: 9 },
  notificationCard: { minHeight: 116, padding: 15, borderRadius: 20, backgroundColor: C.surface, borderWidth: 1, borderColor: C.outline, flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  notificationIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  notificationUrgency: { fontSize: 9, fontWeight: '900', letterSpacing: 0.4 },
  notificationTime: { color: C.textMuted, fontSize: 9 },
  notificationTitle: { color: C.text, fontSize: 14, fontWeight: '800', marginTop: 7 },
  notificationBody: { color: C.textMuted, fontSize: 10, lineHeight: 16, marginTop: 5 },
  profileCard: { minHeight: 88, padding: 15, borderRadius: 22, backgroundColor: C.emphasis, flexDirection: 'row', alignItems: 'center', gap: 12 },
  profileAvatar: { width: 50, height: 50, borderRadius: 17, backgroundColor: '#E5ECFF', alignItems: 'center', justifyContent: 'center' },
  profileName: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  profileCaption: { color: '#AEBBD1', fontSize: 10, marginTop: 4 },
  iconButton: { width: 40, height: 40, borderRadius: 14, backgroundColor: C.primaryContainer, alignItems: 'center', justifyContent: 'center' },
  settingsGroup: { borderRadius: 22, backgroundColor: C.surface, borderWidth: 1, borderColor: C.outline, overflow: 'hidden' },
  districtFeePanel: {
    backgroundColor: C.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.outline,
    padding: 14,
    marginBottom: 16,
  },
  districtSearchInput: {
    minHeight: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.outline,
    backgroundColor: C.background,
    color: C.text,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  districtFeeGroupTitle: {
    color: C.navy,
    fontSize: 15,
    fontWeight: '900',
  },
  districtFeeGroupSpacing: { marginTop: 16 },
  districtRegion: { borderTopWidth: 1, borderTopColor: C.outline },
  districtRegionHeader: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  districtRegionRight: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  districtRegionCount: { color: C.textMuted, fontSize: 11, fontWeight: '700' },
  districtEmptyText: { color: C.textMuted, fontSize: 11, paddingVertical: 10 },
  districtFeeRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: C.outline,
    paddingVertical: 7,
  },
  districtFeeName: {
    flex: 1,
    color: C.text,
    fontSize: 14,
    fontWeight: '800',
  },
  districtFeeInput: {
    width: 104,
    minHeight: 40,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.outline,
    backgroundColor: C.background,
    paddingHorizontal: 10,
    color: C.text,
    textAlign: 'right',
    fontWeight: '800',
  },
  districtFeeUnit: { width: 18, color: C.textMuted, fontSize: 12, fontWeight: '700' },
  settingRow: { minHeight: 76, paddingHorizontal: 15, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 12 },
  settingIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: C.primaryContainer, alignItems: 'center', justifyContent: 'center' },
  settingTitle: { color: C.text, fontSize: 13, fontWeight: '800' },
  settingCaption: { color: C.textMuted, fontSize: 9, marginTop: 4 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,23,42,0.48)' },
  bottomSheet: { paddingHorizontal: 20, paddingBottom: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: C.surface },
  sheetHandle: { width: 42, height: 4, borderRadius: 2, backgroundColor: C.outline, alignSelf: 'center', marginTop: 10, marginBottom: 18 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13 },
  sheetEyebrow: { color: C.primary, fontSize: 9, fontWeight: '800', letterSpacing: 0.8 },
  sheetTitle: { color: C.text, fontSize: 21, fontWeight: '800', marginTop: 4 },
  sheetAddress: { flexDirection: 'row', gap: 8, marginTop: 17, padding: 13, borderRadius: 15, backgroundColor: C.surfaceAlt },
  sheetAddressText: { flex: 1, color: C.text, fontSize: 12, lineHeight: 18 },
  sheetTimeGrid: { flexDirection: 'row', gap: 8, marginTop: 12 },
  sheetTimeItem: { flex: 1, minHeight: 70, padding: 10, borderRadius: 14, backgroundColor: C.surfaceAlt },
  sheetTimeLabel: { color: C.textMuted, fontSize: 8, fontWeight: '700' },
  sheetTimeValue: { color: C.text, fontSize: 15, fontWeight: '800', marginTop: 8 },
  sheetInfoBlock: { marginTop: 12, padding: 13, borderRadius: 15, backgroundColor: C.surfaceAlt },
  sheetInfoLabel: { color: C.textMuted, fontSize: 9, fontWeight: '700' },
  sheetInfoText: { color: C.text, fontSize: 11, lineHeight: 17, marginTop: 5 },
  sheetActions: { flexDirection: 'row', gap: 9, marginTop: 16 },
  scanFab: {
    position: 'absolute',
    right: 18,
    bottom: Platform.OS === 'ios' ? 90 : 82,
    minHeight: 54,
    paddingHorizontal: 18,
    borderRadius: 18,
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#102A65',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 12,
    zIndex: 20,
  },
  scanFabText: { color: C.onPrimary, fontSize: 12, fontWeight: '800' },
  scannerApp: { flex: 1, backgroundColor: C.background },
  scannerHeader: {
    minHeight: 78,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: C.outline,
    backgroundColor: C.surface,
  },
  scannerHeaderCopy: { flex: 1, marginHorizontal: 12 },
  scannerEyebrow: { color: C.primary, fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  scannerTitle: { color: C.text, fontSize: 20, fontWeight: '800', marginTop: 3 },
  scannerStep: {
    minWidth: 40,
    height: 30,
    paddingHorizontal: 9,
    borderRadius: 15,
    backgroundColor: C.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scannerStepText: { color: C.primary, fontSize: 10, fontWeight: '800' },
  scannerContent: { padding: 18, paddingBottom: 36 },
  captureGuide: {
    height: 390,
    borderRadius: 26,
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.outline,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  captureCorner: {
    position: 'absolute',
    width: 58,
    height: 58,
    borderColor: C.primary,
  },
  captureCornerTopLeft: { left: 24, top: 24, borderLeftWidth: 4, borderTopWidth: 4, borderTopLeftRadius: 12 },
  captureCornerTopRight: { right: 24, top: 24, borderRightWidth: 4, borderTopWidth: 4, borderTopRightRadius: 12 },
  captureCornerBottomLeft: { left: 24, bottom: 24, borderLeftWidth: 4, borderBottomWidth: 4, borderBottomLeftRadius: 12 },
  captureCornerBottomRight: { right: 24, bottom: 24, borderRightWidth: 4, borderBottomWidth: 4, borderBottomRightRadius: 12 },
  documentPreview: { width: '75%', alignItems: 'center' },
  documentPreviewTitle: { color: C.text, fontSize: 15, fontWeight: '800', textAlign: 'center', marginTop: 16 },
  documentPreviewCaption: { color: C.textMuted, fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 7 },
  autoCaptureBadge: {
    position: 'absolute',
    bottom: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  autoCaptureDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.success },
  autoCaptureText: { color: C.textMuted, fontSize: 9, fontWeight: '700' },
  captureTips: { flexDirection: 'row', gap: 8, marginTop: 12 },
  captureTip: {
    flex: 1,
    minHeight: 62,
    borderRadius: 16,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  captureTipText: { color: C.textMuted, fontSize: 9, fontWeight: '700' },
  scanPrimaryButton: {
    minHeight: 54,
    borderRadius: 17,
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 15,
  },
  scanPrimaryButtonText: { color: C.onPrimary, fontSize: 12, fontWeight: '800' },
  scanSecondaryButton: {
    minHeight: 52,
    borderRadius: 17,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: '#AFC2EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 9,
  },
  scanSecondaryButtonText: { color: C.primary, fontSize: 11, fontWeight: '800' },
  qualityPreview: {
    height: 285,
    borderRadius: 24,
    backgroundColor: C.surfaceAlt,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qualityImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  qualityDemoImage: { alignItems: 'center', justifyContent: 'center' },
  qualityDemoText: { color: C.textMuted, fontSize: 11, fontWeight: '700', marginTop: 10 },
  documentBoundary: {
    position: 'absolute',
    left: 34,
    right: 34,
    top: 22,
    bottom: 22,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: '#73A0FF',
  },
  qualityScoreCircle: {
    position: 'absolute',
    right: 14,
    top: 14,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qualityScore: { fontSize: 18, fontWeight: '900' },
  qualityScoreLabel: { color: C.textMuted, fontSize: 7, fontWeight: '700' },
  qualityCard: {
    padding: 16,
    borderRadius: 22,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
    marginTop: 12,
  },
  qualityCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  qualityCardTitle: { color: C.text, fontSize: 15, fontWeight: '800' },
  qualityRow: { minHeight: 37, flexDirection: 'row', alignItems: 'center', gap: 9 },
  qualityLabelGroup: { width: 78, flexDirection: 'row', alignItems: 'center', gap: 6 },
  qualityLabel: { color: C.textMuted, fontSize: 9, fontWeight: '700' },
  qualityTrack: { flex: 1, height: 7, borderRadius: 4, backgroundColor: C.surfaceAlt, overflow: 'hidden' },
  qualityFill: { height: '100%', borderRadius: 4 },
  qualityValue: { width: 25, textAlign: 'right', fontSize: 9, fontWeight: '800' },
  qualityWarning: {
    padding: 12,
    marginTop: 9,
    borderRadius: 14,
    backgroundColor: C.warningBg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qualityWarningText: { flex: 1, color: C.warning, fontSize: 10, fontWeight: '700' },
  variantInfo: {
    padding: 13,
    marginTop: 10,
    borderRadius: 15,
    backgroundColor: C.primaryContainer,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  variantInfoText: { flex: 1, color: C.onPrimaryContainer, fontSize: 10, lineHeight: 15, fontWeight: '600' },
  scanActionRow: { flexDirection: 'row', gap: 9, marginTop: 14 },
  scanSecondaryFlex: {
    flex: 0.8,
    minHeight: 52,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#AFC2EB',
    backgroundColor: C.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanPrimaryFlex: {
    flex: 1.2,
    minHeight: 52,
    borderRadius: 17,
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  processingScreen: { flex: 1, paddingHorizontal: 35, alignItems: 'center', justifyContent: 'center' },
  processingIcon: {
    width: 92,
    height: 92,
    borderRadius: 30,
    backgroundColor: C.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  processingTitle: { color: C.text, fontSize: 19, fontWeight: '800', textAlign: 'center', marginTop: 24 },
  processingCaption: { color: C.textMuted, fontSize: 11, lineHeight: 18, textAlign: 'center', marginTop: 8, marginBottom: 25 },
  processingStep: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 11, marginTop: 11 },
  processingStepIcon: { width: 28, height: 28, borderRadius: 10, backgroundColor: C.surfaceAlt, alignItems: 'center', justifyContent: 'center' },
  processingStepIconActive: { backgroundColor: C.success },
  processingStepText: { color: C.text, fontSize: 11, fontWeight: '700' },
  reviewContent: { padding: 18, paddingBottom: 38 },
  ocrSummaryCard: {
    minHeight: 105,
    padding: 17,
    borderRadius: 22,
    backgroundColor: C.emphasis,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ocrSummaryLabel: { color: '#BFCBE0', fontSize: 10, fontWeight: '600' },
  ocrSummaryValue: { color: '#FFFFFF', fontSize: 29, fontWeight: '900', marginTop: 5 },
  ocrSummaryMeta: { alignItems: 'flex-end', gap: 5 },
  ocrSummaryMetaText: { color: '#C7D3E8', fontSize: 9 },
  reviewGuide: {
    marginTop: 10,
    padding: 12,
    borderRadius: 15,
    backgroundColor: C.primaryContainer,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  reviewGuideText: { flex: 1, color: C.onPrimaryContainer, fontSize: 10, lineHeight: 16 },
  ocrFieldCard: {
    marginTop: 10,
    padding: 14,
    borderRadius: 19,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.outline,
  },
  ocrFieldCardWarning: { borderColor: C.danger, backgroundColor: C.dangerBg },
  ocrFieldHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  ocrFieldTitleGroup: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 9 },
  ocrFieldIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: C.primaryContainer, alignItems: 'center', justifyContent: 'center' },
  ocrFieldLabel: { color: C.text, fontSize: 11, fontWeight: '800' },
  ocrFieldSource: { maxWidth: 205, color: C.textMuted, fontSize: 8, marginTop: 3 },
  ocrBadgeRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  confidenceBadge: { height: 27, paddingHorizontal: 8, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 4 },
  confidenceText: { fontSize: 9, fontWeight: '900' },
  ocrFieldInput: {
    minHeight: 45,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.outline,
    backgroundColor: C.background,
    color: C.text,
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 12,
    marginTop: 11,
  },
  ocrFieldInputMultiline: { minHeight: 70, paddingTop: 11, textAlignVertical: 'top' },
  candidateRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  candidateLabel: { color: C.textMuted, fontSize: 8, fontWeight: '700' },
  candidateChip: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9, backgroundColor: C.surfaceAlt },
  candidateChipText: { color: C.primary, fontSize: 8, fontWeight: '700' },
  vendorCheckRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 9 },
  vendorCheckText: { flex: 1, color: C.textMuted, fontSize: 9, fontWeight: '700' },
  privacyNotice: {
    marginTop: 12,
    padding: 13,
    borderRadius: 15,
    backgroundColor: C.successBg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  privacyNoticeText: { flex: 1, color: C.success, fontSize: 9, lineHeight: 14, fontWeight: '600' },
  bottomNavBoundary: {
    backgroundColor: C.surface,
    borderTopWidth: 1,
    borderTopColor: '#CFD7E3',
    shadowColor: '#172033',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.09,
    shadowRadius: 12,
    elevation: 14,
    paddingTop: 6,
  },
  bottomNav: { minHeight: 70, flexDirection: 'row', paddingBottom: 8 },
  navItem: { flex: 1, minHeight: 62, alignItems: 'center', justifyContent: 'center' },
  navIcon: { width: 50, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  navIconSelected: { backgroundColor: C.primaryContainer },
  navLabel: { color: C.textMuted, fontSize: 9, fontWeight: '600', marginTop: 3 },
  navLabelSelected: { color: C.primary, fontWeight: '800' },
  navNotificationDot: { position: 'absolute', right: 9, top: 5, width: 7, height: 7, borderRadius: 4, backgroundColor: C.danger, borderWidth: 1, borderColor: C.surface },
  }));

export type AppStyles = ReturnType<typeof makeStyles>;

export const styles = makeStyles(LIGHT);
